package com.zoho.wms.asyncweb.server.constants;

public class AWSLogConstants
{
    public static final String RECEIVE_PING_FRAME = "Received Ping Frame.";//No I18n
    public static final String DISPATCHING_PAYLOAD = "{0} AWS --> dispatching payload";//No I18n
    public static final String CONNECTION_CLOSED = "AWS --> Connection closed";//No I18n
    public static final String CONNECTION_ERROR = "AWS --> Connection error";//No I18n
    public static final String RECEIVED_PONG_FRAME = "Received Pong Frame.";//No I18n
    public static final String PREPARE_TO_BATCH_PROCESS = "{0} AWS --> prepare to batch process {1}";//No I18n
    public static final String READFRAME_HAS_CONSUMED_DATA_SIZE = "{0} AWS --> ReadFrame has consumed data size={1}";//No I18n
    public static final String DO_FILTER_FALSE = " [DO FILTER - FALSE] {0} . Sending Internal Error";//No I18n
    public static final String GENERALERROR = "[GENERALERROR] {0}";//No I18n
    public static final String RESTRICTED_CONTENTS_IN_MESSAGE = "Restricted contents in message received from {0} . Connection active : {1}";//No I18n
    public static final String WEBENGINE_MSGTRACE_DELAY = "DELAY -> {0}, IP Addr {1}, URL {2}, START TIME {3}, TIME TAKEN {4}";//No I18n
    public static final String WEBENGINE_MSGTRACE_NODELAY = "NODELAY -> {0}, IP Addr {1}, URL {2}, START TIME {3}, TIME TAKEN {4}";//No I18n
    public static final String CANCELLEDKEYEXCEPTION = "CancelledKeyException for the client {0}, ipAddr {1}";//No I18n
    public static final String READFRAME_INCOMPLETE_UNCONSUMED_DATA = "{0} AWS --> ReadFrame incomplete unconsumed data";//No I18n
    public static final String READING_MINUS_ONE_ON_STREAM_MODE = "Reading -1 on stream mode on client {0}, ipAddr {1}";//No I18n
    public static final String INPUT_DATA_SIZE_SET_FOR_CLIENT = "Input Data Size Set For {0}, Size {1}";//No I18n
    public static final String ABNORMAL_SCENARIO = "Abnormal scenario {0}";//No I18n
    public static final String CANCELLEDKEYEXCEPTION_FOR_CLIENT_IN_SETCLOSEAFTERWRITE = "CancelledKeyException for client in setCloseAfterWrite {0}";//No I18n
    public static final String DELAY_IN_REFILLING = "{0} Delay in refilling {1}";//No I18n
    public static final String SEND_ERROR_INVOKED_FOR_CLIENT = "Send error invoked for client {0}, ipAddr {1}";//No I18n
    public static final String CANCELLEDKEYEXCEPTION_IN_HANDLEWRITE = "CancelledKeyException in handleWrite for client {0}, ipAddr {1}, Message {2}";//No I18n
    public static final String INVOKING_NOTIFICATION_TO_SERVLET = "Invoking notification to servlet {0} for client {1}, ipAddr {2}";//No I18n
    public static final String NEW_REQUEST = "NEW_REQUEST client {0}, key {1}, sockport {2}, REQUEST TYPE {3}, RAW URL {4}, HEADERS {5}, PARAM MAP {6}, REQUEST URL {7}";//No I18n
    public static final String REQCOMPLETE = "{0} reqComplete :: {1}" ;//No I18n
    public static final String ON_CLOSE_FOR_CLIENT = "On close for client {0}, ipAddr {1}";//No I18n
    public static final String CONNECTION_ALREADY_CLOSED = "Connection already closed : {0}, ipAddr {1}" ;//No I18n
    public static final String PING_PONG_CLOSE_FRAME_RECEIVED = "PING / PONG / CLOSE Frame received in between WS Continuation frame processing. OPCODE : {0}" ;//No I18n
    public static final String HASUNCONSUMED_DATA = "{0} AWS --> hasUnconsumed data {1}";//No I18n
    public static final String AWS_RF_ADD = "{0} AWS --> RF add {1}";//No I18n
    public static final String USELESS_CODE_CHECK = "Useless code check";//No I18n
    public static final String KEY_NOT_VALID_FOR_CLIENT = "Key not valid for client {0}";//No I18n
    public static final String READ_HANDSHAKE_COMPLETED_FOR_CLIENT = "Read Handshake completed for client {0}, ipAddr {1}";//No I18n
    public static final String HANDSHAKE_COMPLETED_FOR_CLIENT = "Handshake completed for client {0}, ipAdrr {1}";//No I18n
    public static final String IOEXCEPTION_FOR_CLIENT = "IOException for client {0}, ipAddr {1}";//No I18n
    public static final String EXCEPTION_IN_UPDATE_PARAM = "Exception in update param - key : {0}, value : {1}, paramsMap : {2}";//No I18n
    public static final String GETINFO_CALLED_FOR_BANDWIDTHPROFILER = " getInfo called for BandWidthProfiler {0}";//No I18n
    public static final String CLOSE_CALLED_FOR_OLD_RESPONSE_OBJECT = "{0} CLOSE CALLED FOR OLD RESPONSE OBJECT";//No I18n
    public static final String INACTIVE_CONNECTION_CLOSE_ALREADY_DONE = "{0} INACTIVE CONNECTION. CLOSE ALREADY DONE";//No I18n
    public static final String KEEPALIVE_CONNECTION_REINIT_ALREADY_DONE = "{0} KEEPALIVE CONNECTION. REINIT ALREADY DONE";//No I18n
    public static final String PROTOCOL_ERROR = "Protocol Error -- opcode : {0}, fin : {1}, isContinuationFrameInProgress : {2}";//No I18n
    public static final String PROTOCOL_ERROR_PASSED_ALL_IF_AND_RETURN_FALSE = "Protocol Error -- Passed all if and return false. Kindly check this case...";//No I18n
    public static final String AWS_SECURITY_FILTER_SUCCESS = "AWS Security Filter --> USERAUTHENTICATION.SUCCESS : {0}";//No I18n
    public static final String EXCEPTION = "Exception ";//No I18n
    public static final String EXCEPTION_WHILE_CLOSING_SOCKET_CHANNEL = "Exception while closing socket channel ";//No I18n
    public static final String EXCEPTION_DURING_KEY_CANCEL = "Exception during key cancel ";//No I18n
    public static final String INTERRUPTED = "Interrupted - {0}";//No I18n
    public static final String SERVER_ERROR = "Server Error : ";//No I18n
    public static final String RUNTIME_EXCEPTION = "Runtime Exception ";//No I18n
    public static final String SELECTORPOOLERROR = "SelectorPoolError ";//No I18n
    public static final String ISACCEPTABLE_FIRED_IN_READ_SELECTOR = "isAcceptable fired in Read Selector {0}";//No I18n
    public static final String PROBLEN_WITH_KEY_INITIALIZATION = "[UNATTACHED KEY] Problem with key initialization. Closing channel. Duration {0}. Please check.";//No I18n
    public static final String EXCEPTION_DURING_CHANNEL_CLOSE = "Exception during channel close ";//No I18n
    public static final String KEY_HANDLE_STATS = "HTTP[{0}]::Key handle Stats {1}#{2}";//No I18n
    public static final String CHANNEL_TYPE_CASE_EXP = "Channel type case exp ";//No I18n
    public static final String EXCEPTION_FOR_CLIENT = "Exception for client {0}, ipAddr {1}";//No I18n
    public static final String READFRAMECOMPLETED = "{0} AWS --> ReadFrameCompleted {1}";//No I18n
    public static final String READFRAME_NOT_COMPLETE = "{0} AWS --> ReadFrame Not complete";//No I18n
    public static final String INVALID_REQUEST = "Invalid request for client {0}, ipAddr {1}";//No I18n
    public static final String EXCEPTION_IN_REMOVEINDEX = "Exception in removeIndex ";//No I18n
    public static final String SET_CLOSE_BOOLEAN = "Set close boolean {0}";//No I18n
    public static final String SET_REINIT = "Set reinit {0}";//No I18n
    public static final String IGNORING_PROXY_HEADER_ADDRESS_V2_UNSPEC = "Ingnoring proxy header address v2 - UNSPEC ";//No I18n
    public static final String AWS_DEBUG_STRING = "{0}, key {1}, POST - PORT {2}, PARAM MAP {3}, HEADER MAP {4}, REQUEST URL {5}";//No I18n
    public static final String EXCEPTION_WHILE_SETTING_LOG_ID = "Exception while setting log id";//No I18n
    public static final String EXCEPTION_WHILE_SENDING_PONG_FRAME = "Exception while sending pong frame. ";//No I18n
    public static final String EXCEPTION_IN_FORMATTING_ACCESSLOGGER = "Exception in formatting accesslogger ";//No I18n
    public static final String EXCEPTION_IN_INCOMPLETE_REQUEST_DEBUG_LOG = "Exception in incomplete request debug log.";//No I18n
    public static final String EXCEPTION_IN_SERVERCHECK = "Exception in ServerCheck ";//No I18n
    public static final String AWS_REQUEST_TIMEOUT = "AWS Request timeout --> expiredlist size : {0}, errorCase : {1}, reqACK : {2}, readexpired : {3}, closed : {4}";//No I18n
    public static final String TOO_MANY_OPEN_FILES = "Too many open files";//No I18n
    public static final String FILE_DESCRIPTOR = "FileDescriptor debug values --> pid:{0}, fd:{1}";//No I18n
    public static final String SSL_PORT_DOWN = "[SSL PORT MONITORING] {0} is down";//No I18n
    public static final String SSL_HANDSHAKE_EXCEPTION = "SSLHandshakeException : ";//No I18n
    public static final String PORT_MONITOR_IS_RUNNING = "[PORT MONITORING] {0} is running";//No I18n
    public static final String PORT_MONITOR_EXCEPTION = "[PORT MONITORING] Exception while connecting to ";//No I18n
    public static final String PORT_MONITOR_IS_DOWN = "[PORT MONITORING] {0} is down";//No I18n
    public static final String GS_WEBSOCKET_DETAILS = "GS --> WebSocket ws={0}, key={1}, version={2}, sub-protocols={3}, extension={4}, engine={5}, URI={6}";//No I18n
    public static final String IOEXCEPTION_HTTPRESPONSE_CLOSE = "IOException - HttpResponse Close";
    public static final String AWSEXCEPTION_HTTPRESPONSE_CLOSE = "AWSException - HttpResponse Close";
}
