render=ordered_json
usage=ftsloadtest -opr put|get|status|verify [-fs filesize] [-dc dcname] [-cl cluster] [-rid reqid] [-cf copy_file] [-rt read_timeout] [-ct connection_timeout]
-opr=operation
-rid=reqid
-fs=file_size
-dc=dc_name
-cl=cluster
-cf=copy_file
-rt=read_timeout
-ct=connection_timeout